### PR TITLE
Add forbid bad_style and warnings lint check

### PR DESCRIPTION
**Pull request by rossmuir**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/79)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by rossmuir** [comment]
Hey @maqi this ok to merge?

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: 0 of 1 files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/self_encryption/79)

**Comment by dirvine** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- src/lib.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/self_encryption/79)

**Pull request merged**
