### PR TITLE
Avoid re-encrypting chunks if file has not been modified.

### PR DESCRIPTION
**Pull request by Fraser999**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/160)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by lgvz** [comment]
`fn close` will have to be changed also, see #163.

**Comment by lgvz** [comment]
This will fail the test added by #163...

**Comment by brian-js** [comment]
@lgvz Shall I fix it in a separate PR, or would you be ok do it in #163?

**Comment by lgvz** [comment]
@brian-js whatever works for you.

**Comment by brian-js** [comment]
Ok, I'll push a fix that'll allow your new test to pass.

**Pull request merged**
