### PR TITLE
Prepare the window for writing when closing.

### PR DESCRIPTION
**Pull request by brian-js**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/164)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
This PR defeats the purpose of https://github.com/maidsafe/self_encryption/pull/160 - i.e. we'd re-encrypt everything again even if we just read the file.

Closing this in favour of https://github.com/maidsafe/self_encryption/pull/165.

**Comment by brian-js** [comment]
Yeah, just a quick fix to get it green. #160 was clearly unfinished.

**Pull request closed without merging**
