### PR TITLE
refactor/self-encryptor: remove asynchronous code

### PR DESCRIPTION
**Pull request by Fraser999**
This removes the asynchronous library from the project.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/178) &emsp; Multiple assignees:&emsp;@afck&nbsp;<a href="/maidsafe/self_encryption/pulls/assigned/afck">afck</a>,&emsp;@ustulation&nbsp;<a href="/maidsafe/self_encryption/pulls/assigned/ustulation">ustulation</a>

### CODE REVIEW

**Comment by MaidSafe-QA** [comment]
+@afck +@ustulation 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/178#-:-KGm9yJUxYxRi6V8voCc:785007434)*

**Comment by afck** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib.rs, line 364 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/178#-KGmFONnl_CT28d-8Wml:-KGmFONoh-JormUyBGOk:884527906) ([raw file](https://github.com/maidsafe/self_encryption/blob/3889f58a2684d06f246817cea6d880ef780079e1/src/lib.rs#L364)):*
Not sure, but maybe this should still be generic in the `Storage` implementation? Otherwise `storage` is unnecessarily a fat pointer (with all methods virtual), I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/178)*

**Comment by ustulation** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/178)*

**Comment by ustulation** [comment]
Since this is just a minor refactor and the _issues_ are to be dealt in other PR later (that S.E should take in and deal with function signatures that return errors - sp for get's and put's), it's OK from me for this.

**Pull request merged**
