### PR TITLE
Trivial fix for failing test which was exceeding limits for serialisi…

### PR DESCRIPTION
**Pull request by Fraser999**
…ng data via the utilities helpers.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/176)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
*[src/lib.rs, line 1708 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/176#-KEW14_IB9nZJdTyvAP1:-KEW14_IB9nZJdTyvAP2:179760778) ([raw file](https://github.com/maidsafe/self_encryption/blob/9b57d53c92a50ee2d67197e8cc5d32c80bd56e7c/src/lib.rs#L1708)):*
the reducing the length to passing the test is because of the configuration in the code has been changed or just less the stress?
if the latter, probably needs to figure out the real reason why such stress didn't cause trouble previously but now it starts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/176)*

**Comment by Fraser999** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib.rs, line 1708 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/176#-KEW14_IB9nZJdTyvAP1:-KEW2LqZktGR5kwIOHis:2042937579) ([raw file](https://github.com/maidsafe/self_encryption/blob/9b57d53c92a50ee2d67197e8cc5d32c80bd56e7c/src/lib.rs#L1708)):*
The issue arose when we [added limits to serialisation helpers in Utilities](https://github.com/Fraser999/maidsafe_utilities/commit/ff9901fb8699664e12cbeae34e941027c350447f).  We've not noticed it before now because the CI tests for Self-Encryption haven't been triggered.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/176)*

**Comment by maqi** [comment]
*[src/lib.rs, line 1708 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/176#-KEW14_IB9nZJdTyvAP1:-KEW3rbdWhiz94Uldwf7:276652682) ([raw file](https://github.com/maidsafe/self_encryption/blob/9b57d53c92a50ee2d67197e8cc5d32c80bd56e7c/src/lib.rs#L1708)):*
seems the size_limit changed to 2MB, but the max vec_len reduced from 1mB to 200k . is that during the test, the real data passed into serialisation/deserialisation will be about 10 times the data in vec?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/176)*

**Comment by Fraser999** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib.rs, line 1708 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/176#-KEW14_IB9nZJdTyvAP1:-KEWJLaBL7a8tWUntBC4:-1265779432) ([raw file](https://github.com/maidsafe/self_encryption/blob/9b57d53c92a50ee2d67197e8cc5d32c80bd56e7c/src/lib.rs#L1708)):*
Yes - the test serialises `Vec<usize>`, not `Vec<u8>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/176)*

**Comment by maqi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/176)*

**Pull request merged**
