### PR TITLE
Delete trait for SEStorage

### PR DESCRIPTION
**Pull request by kanav99**
Implements delete trait for Storage which is needed for https://github.com/maidsafe/sn_client/pull/1377
This PR needs some tests.

### CODE REVIEW

**Comment by lionel1704** [comment]
Looks good so far. But I think that the `delete()` function is missing from the `SelfEncryptor` struct. 
I imagine that the API would be something like:
```
let encryptor = SelfEncryptor::new(client, root_data_map);
encryptor.delete();
```

**Comment by kanav99** [comment]
I thought that would go in the client, but I think this makes more sense. How should the state of the encryptor look like after delete? should we be able to write to it? or should it be closed?

**Comment by lionel1704** [comment]
I think we can close the self encryptor after calling delete. It can consume the object instead of taking a reference.

**Comment by lionel1704** [comment]
This looks good. It'd be nice to add some tests to this.

**Review by lionel1704 — APPROVED** [review]

**Pull request merged**
