### PR TITLE
Fix truncate

### PR DESCRIPTION
**Pull request by lgvz**
The "next two" problem.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/169) &emsp; Multiple assignees:&emsp;@brian-js&nbsp;<a href="/maidsafe/self_encryption/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/self_encryption/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/self_encryption/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
Hi, there,

I am really sorry for the late notice of your PR.
Could you please update your PR (merging the latest master head into your PR)?
And we will start up the review process asap.
thank you very much.

**Comment by lgvz** [comment]
No problem!

**Comment by maqi** [comment]
+@dirvine +@brian-js : could you please have a double check of the change?
it passes the current tests.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/169#-:-KEY2hbw-BUkCqhGhEzd:-1186253990)*

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/169)*

**Pull request merged**
