### PR TITLE
feat/encryptor: add new sequential encryptor

### PR DESCRIPTION
**Pull request by Fraser999**
This adds a new encryptor which generates chunks and DataMaps compatible with the current
encryptor's, but which only allows sequential writes.  This allows chunks to be stored on the fly,
thus giving more realistic feedback about overall encryption progress.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/191)

### CODE REVIEW

**Comment by dirvine** [comment]
Reviewed 4 of 19 files at r1.
Review status: 4 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[examples/basic_encryptor.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGxPESoY_BwCBHVidD:-KNGxPETk5S8CkKT6zTK:-2106526494) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/examples/basic_encryptor.rs#L36)):*
> ```Rust
> #![cfg_attr(feature="clippy", feature(plugin))]
> #![cfg_attr(feature="clippy", plugin(clippy))]
> #![cfg_attr(feature="clippy", deny(clippy, clippy_pedantic))]
> ```

Are we not now defaulting to just clippy, i.e. no pedantic

---

*[examples/basic_encryptor.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGxsf92RgoVet4gVDj:-KNGxsf92RgoVet4gVDk:-1888772391) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/examples/basic_encryptor.rs#L123)):*
> ```Rust
> impl DiskBasedStorage {
>     fn calculate_path(&self, name: &[u8]) -> PathBuf {
>         let mut path = PathBuf::from(self.storage_path.clone());
> ```

Should storage.path not already be a pathbuf 

---

*[src/error.rs, line 29 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGyEsyFvkXEQQ_mxqb:-KNGyEsyFvkXEQQ_mxqc:297338499) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/error.rs#L29)):*
> ```Rust
> #[derive(Debug)]
> #[cfg_attr(feature="clippy", allow(stutter))]
> pub enum SelfEncryptionError<E: StorageError> {
> ```

Do we need SelfEncryption in this name, or is it for fear of API break?

---

*[src/lib.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGyRsnaFfG5ICPMka2:-KNGyRsnaFfG5ICPMka3:943716236) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/lib.rs#L142)):*
> ```Rust
> #![cfg_attr(feature="clippy", feature(plugin))]
> #![cfg_attr(feature="clippy", plugin(clippy))]
> #![cfg_attr(feature="clippy", deny(clippy, clippy_pedantic))]
> ```

Again I think pedantic should not be used here

---

*[src/lib.rs, line 181 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGyaQXMbiM2jRDwqGG:-KNGyaQXMbiM2jRDwqGH:-1600191287) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/lib.rs#L181)):*
> ```Rust
> /// Controls the compression-speed vs compression-density tradeoffs.  The higher the quality, the
> /// slower the compression.  Range is 0 to 11.
> pub const COMPRESSION_QUALITY: u32 = 6;
> ```

Have we tested via benchmarks? Poss we only need a low level here. 

---

*[src/sequencer.rs, line 157 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH-gNfciE9TQ10fevg:-KNH-gNgAJ_byGXTpdiF:259129879) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequencer.rs#L157)):*
> ```Rust
> impl Deref for Sequencer {
>     type Target = [u8];
>     fn deref(&self) -> &[u8] {
> ```

Not clear why this is here? We have clone_from_slice etc. now 

---

*[src/storage.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH-sFaAAEWWbNAg_4l:-KNH-sFaAAEWWbNAg_4m:1762429096) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/storage.rs#L23)):*
> ```Rust
> /// `Storage` object.
> #[cfg_attr(feature="clippy", allow(stutter))]
> pub trait StorageError: Error {}
> ```

Again be nice not to have Storage i this name.

---

*[src/sequential/encryptor.rs, line 77 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH0v_-E0AN9Ao6JMd-:-KNH0v_0mWoEQREvxZ0W:-1841766091) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/encryptor.rs#L77)):*
> ```Rust
> }
> 
> impl<'a, E: StorageError, S: Storage<E>> Encryptor<'a, E, S> {
> ```

This seems a bit complex, perhaps a quick HO with @afck  and @ustulation would be good here to clarify the generics  

---

*[src/sequential/encryptor.rs, line 79 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH0S2pZ6F7gnHO-oDU:-KNH0S2pZ6F7gnHO-oDV:-1456209105) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/encryptor.rs#L79)):*
> ```Rust
> impl<'a, E: StorageError, S: Storage<E>> Encryptor<'a, E, S> {
>     /// Creates an `Encryptor`, using an existing `DataMap` if `data_map` is not `None`.
>     pub fn new(storage: &'a mut S,
> ```

Is it better to have `new()` or default() and also a `from_data_map()`

---

*[src/sequential/large_encryptor.rs, line 131 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH1R_5cmit0h949jC-:-KNH1R_5cmit0h949jC0:1973380894) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/large_encryptor.rs#L131)):*
> ```Rust
>     // exception is where the encryptor didn't receive any `write()` calls, in which case no chunks
>     // are stored.
>     pub fn close(&mut self) -> Result<DataMap, SelfEncryptionError<E>> {
> ```

If this did return the datamap then it would probably be better for later, maybe the TODO could indicate this. Then we set a closed flag or drop reference  etc. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/191)*

**Comment by afck** [comment]
Review status: 4 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/sequential/encryptor.rs, line 77 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH0v_-E0AN9Ao6JMd-:-KNH3EuMnc5rrd7myW3I:-1812734174) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/encryptor.rs#L77)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> This seems a bit complex, perhaps a quick HO with @afck  and @ustulation would be good here to clarify the generics  
</details>
Would it make sense to make `StorageError` a dependent type in `Storage` (like `Item` in `Iterator`)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/191)*

**Comment by Fraser999** [comment]
Review status: 4 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[examples/basic_encryptor.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGxPESoY_BwCBHVidD:-KNH4d0-hGstjPeA4kf9:-1332105613) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/examples/basic_encryptor.rs#L36)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Are we not now defaulting to just clippy, i.e. no pedantic
</details>
Updated to remove pedantic

---

*[examples/basic_encryptor.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGxsf92RgoVet4gVDj:-KNH6WC_Qfs5HxiH7dM1:1600698796) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/examples/basic_encryptor.rs#L123)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Should storage.path not already be a pathbuf 
</details>
Yeah - it probably should be, but this example could probably do with a bit of an overhaul.  I was just trying to limit my changes to the new sequential encryptor stuff and fixing clippy warnings.

---

*[src/error.rs, line 29 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGyEsyFvkXEQQ_mxqb:-KNH5Eb3qavWBAGFqka9:-1241269289) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/error.rs#L29)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Do we need SelfEncryption in this name, or is it for fear of API break?
</details>
I think it may be the `Error` part that's causing the lint failure, but yeah - avoiding breaking the API :)

---

*[src/lib.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNGyRsnaFfG5ICPMka2:-KNH_jkoWaBcnyxdjA_p:-499146009) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/lib.rs#L142)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Again I think pedantic should not be used here
</details>
Done.

---

*[src/sequential/encryptor.rs, line 79 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH0S2pZ6F7gnHO-oDU:-KNHoiYgesAnQUlK_e2i:-1395264604) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/encryptor.rs#L79)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Is it better to have `new()` or default() and also a `from_data_map()`
</details>
Added todo for this.

---

*[src/sequential/large_encryptor.rs, line 131 \[r1\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/191#-KNH1R_5cmit0h949jC-:-KNHomMSZ8njSlVgdEy2:-582234568) ([raw file](https://github.com/maidsafe/self_encryption/blob/c48852e7d3bdc5c234577150fcda9f2e3eac236a/src/sequential/large_encryptor.rs#L131)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> If this did return the datamap then it would probably be better for later, maybe the TODO could indicate this. Then we set a closed flag or drop reference  etc. 
</details>
Added todo for changing signature to `mut self`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/191)*

**Comment by dirvine** [comment]
Reviewed 1 of 19 files at r1, 1 of 11 files at r2.
Review status: 6 of 20 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/191)*

**Comment by dirvine** [comment]
Reviewed 4 of 19 files at r1, 9 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/191)*

**Pull request merged**
