### PR TITLE
Determinism, WIP.

### PR DESCRIPTION
**Pull request by s-brian**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/73)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: 0 of 3 files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/self_encryption/73)

**Comment by s-brian** [comment]
Looks like compression is indeed the culprit. Should I do a PR with that removed and we can find/write a cross platform compression lib later?

**Comment by dirvine** [comment]
Are you happy with this now?

---

Review status: 0 of 3 files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/self_encryption/73)

**Comment by s-brian** [comment]
I'm satisfied that I've tested the different levels of compression and the test fails when moved across OS's. Without compression the test is ok. As such, I'd be happy to have it merged.

**Comment by dirvine** [comment]
Review status: 0 of 3 files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- Cargo.toml @ r1
- src/lib.rs @ r1
- tests/lib.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/self_encryption/73)

**Pull request merged**
