### PR TITLE
refactor/all: use `Result`s throughout

### PR DESCRIPTION
**Pull request by Fraser999**
This changes all the public functions which can have errors to return `Result`s.  Also improved
documentation and removed two unneeded tests.

For the reviewer: I split the changes into two commits to make the review easier.  The first commit only contains the changes around splitting lib.rs up - there were no logic changes there at all.  So, really only the second commit is interesting from a reviewer's perspective I think.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/self_encryption/185)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 3 of 12 files at r1, 2 of 4 files at r2, 1 of 1 files at r3.
Review status: 5 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/data_map.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/185#-KIYgXIt0gJWtvIEqpPU:-KIYgXIt0gJWtvIEqpPV:965463815) ([raw file](https://github.com/maidsafe/self_encryption/blob/83a689fedbd56da9b8395fbeeeb04b8504c3af88/src/data_map.rs#L44)):*
> ```Rust
>         let mut ret = String::new();
>         for byte in input_ref.iter() {
>             write!(ret, "{:02x}", byte).expect("");
> ```

Can you please put descriptive text in `expect` calls,  Just helps debug / error reporting 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by dirvine** [comment]
Reviewed 5 of 12 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/data_map.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/185#-KIYgXIt0gJWtvIEqpPU:-KIb4HscJk20Ipwn8xSZ:692778593) ([raw file](https://github.com/maidsafe/self_encryption/blob/83a689fedbd56da9b8395fbeeeb04b8504c3af88/src/data_map.rs#L44)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> Can you please put descriptive text in `expect` calls,  Just helps debug / error reporting 
</details>
Do you want unique messages, or can I duplicate all for a given function e.g. all `write()`s become `write(...).expect("Should have written")`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/data_map.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/185#-KIYgXIt0gJWtvIEqpPU:-KIb991tuaOqgSys5MlM:564095231) ([raw file](https://github.com/maidsafe/self_encryption/blob/83a689fedbd56da9b8395fbeeeb04b8504c3af88/src/data_map.rs#L44)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> Do you want unique messages, or can I duplicate all for a given function e.g. all `write()`s become `write(...).expect("Should have written")`?
</details>
As unique as possible as these will print out on failure. So an indication of where it is, like "shoudl have written in seq" etc. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/data_map.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/185#-KIYgXIt0gJWtvIEqpPU:-KIbA2k3U7g8SMQjGTGA:-1697475340) ([raw file](https://github.com/maidsafe/self_encryption/blob/83a689fedbd56da9b8395fbeeeb04b8504c3af88/src/data_map.rs#L44)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> As unique as possible as these will print out on failure. So an indication of where it is, like "shoudl have written in seq" etc. 
</details>
OK.  This will take me a wee while, since there are 163 occurrences (all in tests/examples/benchmarks except this debug printout one which can't fire anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/data_map.rs, line 44 \[r3\]](https://reviewable.io:443/reviews/maidsafe/self_encryption/185#-KIYgXIt0gJWtvIEqpPU:-KIbD1X3OtQLIxaIaS1A:-1398069047) ([raw file](https://github.com/maidsafe/self_encryption/blob/83a689fedbd56da9b8395fbeeeb04b8504c3af88/src/data_map.rs#L44)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> OK.  This will take me a wee while, since there are 163 occurrences (all in tests/examples/benchmarks except this debug printout one which can't fire anyway).
</details>
In tests that should be small then use `unwrap()` if it simpler (unit tests only I would say - so small simple tests where this is called only once), the [point is these being blank is then they are just `unwrap()` filled in with unique string will tell where they failed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 5 of 12 files at r1, 1 of 4 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Comment by dirvine** [comment]
Reviewed 1 of 4 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/self_encryption/185)*

**Pull request merged**
